### ISSUE TITLE
FacadeTrait::testServiceProvider() calls nonexistent method.

### ISSUE THREAD

**Issue by aejnsn** [GrahamCampbell/Laravel-TestBench-Core#3]
I've noticed [this line](https://github.com/GrahamCampbell/Laravel-TestBench-Core/blob/master/src/FacadeTrait.php#L103) in `FacadeTrait` is making a call to method `assertInArray($needle, $haystack, $msg = '')` in `HelperTrait`. However `HelperTrait`defines the `assertInArray()` method with only three parameters, and the method is being called in `FacadeTrait` with four parameters.

When using `FacadeTrait` in testing facades this is causing tests to fail. I have changed the call in `FacadeTrait` to the following and it seems to be fixed:
`$this->assertInArray($accessor, $method->invoke(new $provider($this->app)), $msg);`

Should I PR this change?

**Comment by GrahamCampbell** [comment]
You need to load in the trait that defines that method. :)
